name: Python CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '**/scripts/**'           
      - 'data/**'                  
      - 'requirements.txt'         
      - '.github/workflows/**'    
  pull_request:
    branches:
      - main
    paths:
      - '**/scripts/**'           
      - 'data/**'                  
      - 'requirements.txt'         
      - '.github/workflows/**'    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.10' 

      - name: Install distutils and build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils build-essential


      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip  
            venv/         
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}-python-${{ runner.python-version }}
          restore-keys: |
            ${{ runner.os }}-python-


      - name: Set up virtual environment
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment


      - name: Install dependencies
        run: |
          source venv/bin/activate  # Ensure virtual environment is activated
          python -m pip install --upgrade pip
          python -m pip install setuptools==75.0.0 wheel==0.40.0  # Ensuring specific versions
          python -m pip install --prefer-binary -r requirements.txt  # Install dependencies

      - name: Check if data folder is empty
        id: check-data-folder
        run: |
          if [ -z "$(ls -A data)" ]; then
            echo "is_empty=true" >> $GITHUB_ENV
          else
            echo "is_empty=false" >> $GITHUB_ENV
          fi

      - name: Skip scripts if data folder is empty
        if: env.is_empty == 'true'
        run: |
          echo "The data folder is empty. Skipping script execution."

      - name: Run scripts
        if: env.is_empty == 'false'
        run: |
          source venv/bin/activate  # Ensure virtual environment is activated
          python ./scripts/ADV_script.py  
          python ./scripts/DR_script.py  
          python ./scripts/DIP_script.py
          python ./scripts/RTD_script.py
          python ./scripts/RTS_script.py


      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./reports/
