name: Python CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.12'  

      - name: Install distutils and build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install setuptools==75.0.0 wheel==0.40.0
          pip install --prefer-binary -r requirements.txt  

      - name: Run scripts
        run: |
          python path/to/your/ADV_script.py  
          python path/to/your/DR_script.py  
          python path/to/your/DIP_script.py
          python path/to/your/RTD_script.py
          python path/to/your/RTS_script.py

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./reports/
