name: Python CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'requirements.txt'
      - '.github/workflows/**'
      - 'scripts/**'
      - 'data/**/*.xlsx'  
  pull_request:
    branches:
      - main
    paths:
      - 'requirements.txt'
      - '.github/workflows/**'
      - 'scripts/**'
      - 'data/**/*.xlsx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for .xlsx files in the data folder
        id: check_xlsx
        run: |
          if [ -z "$(find data -type f -name '*.xlsx' 2>/dev/null)" ]; then
            echo "No .xlsx files found in the data folder."
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo ".xlsx files found in the data folder."
            echo "skip_build=false" >> $GITHUB_ENV
          fi

      - name: Stop workflow if no .xlsx files are found
        if: env.skip_build == 'true'
        run: |
          echo "Skipping the workflow since no .xlsx files are present in the data folder."
          exit 0

      - name: Set up Python
        if: env.skip_build != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install distutils and build-essential
        if: env.skip_build != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils build-essential

      - name: Cache pip dependencies
        if: env.skip_build != 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv/
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}-python-${{ runner.python-version }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Set up virtual environment
        if: env.skip_build != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        if: env.skip_build != 'true'
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install setuptools==75.0.0 wheel==0.40.0
          python -m pip install --prefer-binary -r requirements.txt

      - name: Run scripts
        if: env.skip_build != 'true'
        run: |
          source venv/bin/activate
          python ./scripts/ADV_script.py
          python ./scripts/DR_script.py
          python ./scripts/DIP_script.py
          python ./scripts/RTD_script.py
          python ./scripts/RTS_script.py

      - name: Upload reports as artifacts
        if: env.skip_build != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./reports/
