name: Python CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.10'  # Using Python 3.10 for better compatibility

      - name: Install distutils and build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils build-essential

      - name: Set up virtual environment
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==75.0.0 wheel==0.40.0  # Ensuring specific versions
          python -m pip install -v --no-cache-dir --prefer-binary -r requirements.txt  # Install dependencies with verbose output

      - name: Run scripts
        run: |
          python ./scripts/ADV_script.py  
          python ./scripts/DR_script.py  
          python ./scripts/DIP_script.py
          python ./scripts/RTD_script.py
          python ./scripts/RTS_script.py

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./reports/
